import { Inter } from "next/font/google";
import "./globals.css";
import MainFooter from "@/components/main-footer/main-footer";
import MainHeader from "@/components/main-header/main-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />

        {children}
        <MainFooter />
      </body>

    </html>
  );
}
